apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitlist
spec:  
  results:
      - name: actudepo
  params:
      - name: IMAGE
        type: string
      - name: USER_HOME
        description: |
          clona un repositorio, modifica su contenido y lo pushea
        type: string
        default: "/root"
  workspaces:
    - name: output
    - name: auth-git
      optional: true
  steps:
  - name: repoupdate
    image: alpine/git:latest
    script: |
     #!/usr/bin/env sh
     v=$IMAGE
     echo $v
     cp "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}/.git-credentials" "${PARAM_USER_HOME}/.git-credentials"
     cp "${WORKSPACE_BASIC_AUTH_DIRECTORY_PATH}/.gitconfig" "${PARAM_USER_HOME}/.gitconfig"
     chmod 400 "${PARAM_USER_HOME}/.git-credentials"
     chmod 400 "${PARAM_USER_HOME}/.gitconfig"
     git clone https://github.com/daraxta/Kube
     cd Kube
     ls
     git config --global user.name "David"
     git config --global user.email "admin2314@yopmail.com"
     sed -ri "s#davidrv17/pythonapp:.*#$v#g" kubernetes/deployment.yaml
     cat kubernetes/deployment.yaml | grep "davidrv17"
     git add .
     git commit -m "UltimaVersion"
     git push origin main
    env: 
    - name: IMAGE
      value: $(params.IMAGE)
    - name: PARAM_USER_HOME
      value: $(params.USER_HOME)
    - name: WORKSPACE_BASIC_AUTH_DIRECTORY_PATH
      value: $(workspaces.auth-git.path)
    workingDir: $(workspaces.output.path)


  
